import HashTable
t1=HashTable.HashTable(10)

t1.Insert('One',1)
t1.Insert('Two',2)
t1.Insert('Three',3)
t1.Insert('Four',4)
t1.Insert('Five',5)
t1.Insert('Six',6)
t1.Insert('Seven',7)
t1.Insert('Eight',8)
print('----------------------------------')
t1.PrintArray()
print('Size of array:',len(t1.table))
print('load factor:',t1.n/t1.m)
print('As the load factor is greater than 0.75, rehashing will take place at next insertion')
t1.Insert('Nine',9)
print('----------------------------------')
t1.PrintArray()
print('Size of array:',len(t1.table))
print('Rehashing has been taken place and the array has been resized from 10 to 20')
t1.Insert('Ten',10)
t1.Insert('Eleven',11)
t1.Insert('Tweleve',12)
print('----------------------------------')
t1.PrintArray()
print('Size of array:',len(t1.table))
print("The array has been resized to 20 due to the load factor reaching 0.75")
print("Deleting elements to reach a load factor of 0.1 ")
t1.Delete('One')
t1.Delete('Two')
t1.Delete('Three')
t1.Delete('Four')
t1.Delete('Five')
t1.Delete('Six')
t1.Delete('Seven')
t1.Delete('Eight')
t1.Delete('Nine')
t1.Delete('Ten')
print('------------------------------')
t1.PrintArray()
print('Size of array:',len(t1.table))
print('Rehashing has been taken place and the array has been resized from 20 to 10')
